// Generated by https://quicktype.io

interface IDOMElement {
    selector: string;
}

export interface Vocabulary extends IDOMElement {
    version:     number;
    text:        string;
    pos:         string;
    ipa:         string;
    audio:       string;
    definitions: Definition[];
    //phrasal_verb: string[];
    //idioms: string[];
}

export interface Definition {
    version:   number;
    def:       string;
    def_gram:  string;
    def_trans: string;
    pos:       string;
    guideword: string;
    examples:  Example[];
}

export interface Example {
    version: number;
    eg:      string;
    trans:   string;
}
